# =============================================================================
# CUCP One-Click Installer
# =============================================================================
# Usage (PowerShell):
#   git clone https://github.com/bagseunggwon30-cyber/Computer-Use-Control-Plane.git
#   cd cucp
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\install.ps1
#
# What this does:
#   1. Checks for PowerShell 5.1+ on Windows.
#   2. Creates a user-scope `cucp` shim for scripts/cucp.ps1.
#   3. Verifies the wrapper with health-quick.
#   4. Prints next-step guidance.
#
# Safety:
#   - No admin/UAC required. Uses only the current user's shim folder.
#   - Does not change system files or registry.
#   - To undo, remove the generated `cucp.cmd` shim from the configured BinDir.
# =============================================================================
[CmdletBinding()]
param(
    # Folder for the generated cucp command shim. WindowsApps is usually on PATH.
    [string]$BinDir = (Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps'),
    [switch]$NoPathShim,   # Skip shim creation and run only from the clone.
    [switch]$Quiet
)

$ErrorActionPreference = 'Stop'
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch { }

function Write-Step { param([string]$m) if (-not $Quiet) { Write-Host ("  " + $m) } }
function Write-Ok   { param([string]$m) if (-not $Quiet) { Write-Host ("  [OK] " + $m) -ForegroundColor Green } }
function Write-Warn { param([string]$m) if (-not $Quiet) { Write-Host ("  [!] " + $m) -ForegroundColor Yellow } }
function Write-Err  { param([string]$m) Write-Host ("  [X] " + $m) -ForegroundColor Red }

if (-not $Quiet) {
    Write-Host ""
    Write-Host "  CUCP installer" -ForegroundColor Cyan
    Write-Host "  ==============="
    Write-Host ""
}

# --- 1. Environment checks -------------------------------------------------
$psMajor = $PSVersionTable.PSVersion.Major
if ($psMajor -lt 5) {
    Write-Err "PowerShell 5.1+ required (found $($PSVersionTable.PSVersion)). Install Windows PowerShell 5.1 or PowerShell 7+."
    exit 1
}
Write-Ok "PowerShell $($PSVersionTable.PSVersion)"

$isWin = $true
try {
    if ($null -ne (Get-Variable -Name IsWindows -ErrorAction SilentlyContinue)) { $isWin = [bool]$IsWindows }
    else { $isWin = ([Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT) }
} catch { $isWin = $true }
if (-not $isWin) {
    Write-Err "CUCP requires Windows 10/11 (uses Win32 / UIA / Windows.Media.Ocr). Detected non-Windows OS."
    exit 1
}
Write-Ok "Windows detected"

# --- 2. Path checks --------------------------------------------------------
$repoRoot = $PSScriptRoot
$wrapper  = Join-Path $repoRoot 'scripts\cucp.ps1'
if (-not (Test-Path -LiteralPath $wrapper)) {
    Write-Err "scripts\cucp.ps1 not found next to install.ps1. Run this from the cloned repo root."
    exit 1
}
Write-Ok "wrapper found: scripts\cucp.ps1"

# --- 3. PATH shim ----------------------------------------------------------
# Create a .cmd shim so `cucp ...` works from any directory.
# The default BinDir (WindowsApps) is usually already on PATH.
if (-not $NoPathShim) {
    try {
        if (-not (Test-Path -LiteralPath $BinDir)) { New-Item -ItemType Directory -Path $BinDir -Force | Out-Null }
        $shimPath = Join-Path $BinDir 'cucp.cmd'
        # Forward all arguments to cucp.ps1. Quote the wrapper path for spaces.
        $shim = "@echo off`r`n" +
                "rem CUCP launcher shim. Generated by install.ps1.`r`n" +
                'powershell -NoProfile -ExecutionPolicy Bypass -File "' + $wrapper + '" %*' + "`r`n"
        [System.IO.File]::WriteAllText($shimPath, $shim, [System.Text.Encoding]::ASCII)
        Write-Ok "shim created: $shimPath"

        $onPath = ($env:PATH -split ';') -contains $BinDir
        if ($onPath) {
            Write-Ok "'$BinDir' is already on PATH -> you can run: cucp macro windows"
        } else {
            Write-Warn "'$BinDir' is NOT on PATH. Add it, or run cucp via full path."
        }
    } catch {
        Write-Warn "shim creation failed ($($_.Exception.Message)). You can still run cucp via: scripts\cucp.ps1"
    }
} else {
    Write-Step "skipped PATH shim (-NoPathShim)."
}

# --- 4. 동작 검증 -----------------------------------------------------------
Write-Step ""
Write-Step "verifying (macro health-quick)..."
try {
    $out = & powershell -NoProfile -ExecutionPolicy Bypass -File $wrapper -Brief macro health-quick 2>&1 | Out-String
    if ($out -match 'ok health|passed=') {
        Write-Ok "health-quick passed"
    } else {
        Write-Warn "health-quick ran but output was unexpected:"
        if (-not $Quiet) { Write-Host ($out.Trim()) }
    }
} catch {
    Write-Warn "health-quick check failed: $($_.Exception.Message)"
}

# --- 5. 다음 단계 안내 ------------------------------------------------------
if (-not $Quiet) {
    Write-Host ""
    Write-Host "  Done. Try these:" -ForegroundColor Cyan
    Write-Host "    cucp macro windows                 # list open windows (read-only)"
    Write-Host "    cucp version                       # show component versions"
    Write-Host "    cucp -AllowLiveControl macro smart-click --label Save --match Notepad"
    Write-Host ""
    Write-Host "  Docs: README.md  |  Full macros: references/command-reference.md"
    Write-Host ""
}
exit 0
