# =============================================================================
# CUCP One-Click Installer
# =============================================================================
# 사용법 (PowerShell):
#   git clone https://github.com/bagseunggwon30-cyber/cucp.git
#   cd cucp
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\install.ps1
#
# 하는 일:
#   1. PowerShell 5.1+ / Windows 확인
#   2. cucp.ps1 진입점을 PATH 에서 부를 수 있게 `cucp` shim 을 사용자 폴더에 생성
#   3. health-quick 으로 동작 검증
#   4. 다음에 할 일 안내
#
# 안전:
#   - 관리자 권한(UAC) 불필요. 현재 사용자 범위(HKCU/사용자 폴더)만 사용.
#   - 시스템 파일/레지스트리 변경 없음. 되돌리려면 생성된 shim 파일만 삭제.
# =============================================================================
[CmdletBinding()]
param(
    # shim(cucp 명령)을 둘 폴더. 기본은 사용자 WindowsApps(보통 PATH 에 이미 포함).
    [string]$BinDir = (Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps'),
    [switch]$NoPathShim,   # shim 생성 건너뛰기 (clone 위치에서 직접 실행만)
    [switch]$Quiet
)

$ErrorActionPreference = 'Stop'
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch { }

function Write-Step { param([string]$m) if (-not $Quiet) { Write-Host ("  " + $m) } }
function Write-Ok   { param([string]$m) if (-not $Quiet) { Write-Host ("  [OK] " + $m) -ForegroundColor Green } }
function Write-Warn { param([string]$m) if (-not $Quiet) { Write-Host ("  [!] " + $m) -ForegroundColor Yellow } }
function Write-Err  { param([string]$m) Write-Host ("  [X] " + $m) -ForegroundColor Red }

if (-not $Quiet) {
    Write-Host ""
    Write-Host "  CUCP installer" -ForegroundColor Cyan
    Write-Host "  ==============="
    Write-Host ""
}

# --- 1. 환경 점검 -----------------------------------------------------------
$psMajor = $PSVersionTable.PSVersion.Major
if ($psMajor -lt 5) {
    Write-Err "PowerShell 5.1+ required (found $($PSVersionTable.PSVersion)). Install Windows PowerShell 5.1 or PowerShell 7+."
    exit 1
}
Write-Ok "PowerShell $($PSVersionTable.PSVersion)"

$isWin = $true
try {
    if ($null -ne (Get-Variable -Name IsWindows -ErrorAction SilentlyContinue)) { $isWin = [bool]$IsWindows }
    else { $isWin = ([Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT) }
} catch { $isWin = $true }
if (-not $isWin) {
    Write-Err "CUCP requires Windows 10/11 (uses Win32 / UIA / Windows.Media.Ocr). Detected non-Windows OS."
    exit 1
}
Write-Ok "Windows detected"

# --- 2. 경로 확인 -----------------------------------------------------------
$repoRoot = $PSScriptRoot
$wrapper  = Join-Path $repoRoot 'scripts\cucp.ps1'
if (-not (Test-Path -LiteralPath $wrapper)) {
    Write-Err "scripts\cucp.ps1 not found next to install.ps1. Run this from the cloned repo root."
    exit 1
}
Write-Ok "wrapper found: scripts\cucp.ps1"

# --- 3. PATH shim 생성 ------------------------------------------------------
# `cucp ...` 한 단어로 어디서든 부를 수 있게 .cmd shim 을 BinDir 에 만든다.
# BinDir 기본값(WindowsApps)은 대부분 PATH 에 이미 등록돼 있어 즉시 동작.
if (-not $NoPathShim) {
    try {
        if (-not (Test-Path -LiteralPath $BinDir)) { New-Item -ItemType Directory -Path $BinDir -Force | Out-Null }
        $shimPath = Join-Path $BinDir 'cucp.cmd'
        # %* 로 모든 인자를 그대로 cucp.ps1 에 전달. 경로는 "..." 로 감싸 공백 안전.
        $shim = "@echo off`r`n" +
                "rem CUCP launcher shim. Generated by install.ps1.`r`n" +
                'powershell -NoProfile -ExecutionPolicy Bypass -File "' + $wrapper + '" %*' + "`r`n"
        [System.IO.File]::WriteAllText($shimPath, $shim, [System.Text.Encoding]::ASCII)
        Write-Ok "shim created: $shimPath"

        $onPath = ($env:PATH -split ';') -contains $BinDir
        if ($onPath) {
            Write-Ok "'$BinDir' is already on PATH -> you can run: cucp macro windows"
        } else {
            Write-Warn "'$BinDir' is NOT on PATH. Add it, or run cucp via full path."
        }
    } catch {
        Write-Warn "shim creation failed ($($_.Exception.Message)). You can still run cucp via: scripts\cucp.ps1"
    }
} else {
    Write-Step "skipped PATH shim (-NoPathShim)."
}

# --- 4. 동작 검증 -----------------------------------------------------------
Write-Step ""
Write-Step "verifying (macro health-quick)..."
try {
    $out = & powershell -NoProfile -ExecutionPolicy Bypass -File $wrapper -Brief macro health-quick 2>&1 | Out-String
    if ($out -match 'ok health|passed=') {
        Write-Ok "health-quick passed"
    } else {
        Write-Warn "health-quick ran but output was unexpected:"
        if (-not $Quiet) { Write-Host ($out.Trim()) }
    }
} catch {
    Write-Warn "health-quick check failed: $($_.Exception.Message)"
}

# --- 5. 다음 단계 안내 ------------------------------------------------------
if (-not $Quiet) {
    Write-Host ""
    Write-Host "  Done. Try these:" -ForegroundColor Cyan
    Write-Host "    cucp macro windows                 # list open windows (read-only)"
    Write-Host "    cucp version                       # show component versions"
    Write-Host "    cucp -AllowLiveControl macro smart-click --label Save --match Notepad"
    Write-Host ""
    Write-Host "  Docs: README.md  |  Full macros: references/command-reference.md"
    Write-Host ""
}
exit 0
